feat: initial documentation
Pure-Farming/Documentation pull request #1
Opened 2022-10-18 22:18 UTC by daniel-buchanan

----

**Notes**
This PR includes the landing page and common objects.

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [x] Links work to navigate documentation
- [x] Images stored in `_images`
- [x] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-10-18 23:10 UTC, sb226 submitted a review, later dismissed

2022-10-18 23:28 UTC, danielR9 reviewed
How much of that html do we actually need here? Can some of it be created from markdown with the plugin (I understand the plugin does the md -> html before publishing on wordpress)

2022-10-18 23:30 UTC, danielR9 requested changes
A couple of bugs in the formatting

![image](https://user-images.githubusercontent.com/20057652/196563865-2f566126-7e2c-4177-badd-1f4851db7a1f.png)

![image](https://user-images.githubusercontent.com/20057652/196563896-87b6f282-07be-48d1-a228-1a10e2cea138.png)

![image](https://user-images.githubusercontent.com/20057652/196563931-eef0bdfd-dc04-4227-bfcb-ce9e2a05501e.png)

2022-10-18 23:42 UTC, daniel-buchanan commented
> A couple of bugs in the formatting
> 
> ![image](https://user-images.githubusercontent.com/20057652/196563865-2f566126-7e2c-4177-badd-1f4851db7a1f.png)
> 
> ![image](https://user-images.githubusercontent.com/20057652/196563896-87b6f282-07be-48d1-a228-1a10e2cea138.png)
> 
> ![image](https://user-images.githubusercontent.com/20057652/196563931-eef0bdfd-dc04-4227-bfcb-ce9e2a05501e.png)

@danielR9  these are intentional to re-use the WP styles so things appear as they are now (so that we get the best UX overall). But we can finesse that in time.

2022-10-19 00:11 UTC, danielR9 approved these changes

2022-10-19 01:31 UTC, merged