chore: ini documentation
Pure-Farming/Documentation pull request #14
Opened 2022-11-20 21:50 UTC by chrishogg

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-11-21 23:37 UTC, daniel-buchanan requested changes
Some minor changes.
Question about the analysis @chrishogg these look like they would be common across several resource types? Or is that something we should look at in future?

2022-11-21 23:37 UTC, daniel-buchanan commented on docs/resource-types/dairy/milk-collection.md
> +- [URLs]()
```suggestion
- [URLs](#urls)
```

2022-11-21 23:37 UTC, daniel-buchanan commented on docs/resource-types/dairy/milk-collection.md
> +- [Response Structure]()
```suggestion
- [Response Structure](#response-structure)
```

2022-11-21 23:37 UTC, daniel-buchanan commented on docs/resource-types/index.md
> +- [Dairy](/resource-types/dairy
```suggestion
- [Dairy](/resource-types/dairy)
```

2022-11-22 00:01 UTC, VicXue commented
> Some minor changes. Question about the analysis @chrishogg these look like they would be common across several resource types? Or is that something we should look at in future?

I took this from Chris as he is busy with other changes due to new schema structure. Since we have already decided that milk collection would inherit the load resource json schema, I don't see why we can't re-use some of the existing model definitions.

2022-11-23 20:28 UTC, daniel-buchanan approved these changes

2022-11-23 20:46 UTC, merged