feat(animal-group): documentation for animal group
Pure-Farming/Documentation pull request #15
Opened 2022-11-24 03:32 UTC by ryanjosephtorrado

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +- [Response Structure]()
I think these need actual links to the sections below

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +| **Primary Breed**       | ICAR breed code for this Animal Group. For example:<br/>`{ "scheme": "ICAR2", "id": "AN" }`<br/>For more details, see also Reference Data Breeds - PureFarming DevHub | Ind
*Identifier
Also link to the common identifier object

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +| **Count**               | The count or number of animals in this inventory classification                                                                                                       | Dec
Not sure what we are doing elsewhere but I'm not so sure on `Decimal`, I think I would prefer `Number`? (or integer, but its not an int in the schema I don't think

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +  "species": "String"
```suggestion
  "birthPeriod": "string",
  "count": 1,
  "lactationStatus": "string",
  "name": "string",
  "primaryBreed": {...},
  "productionPurposes": [...],
  "reproductiveStatus": "string",
  "sex": "string",
  "species": "string"
```

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +| **Meta**           | Meta data for the resource                                                                     | Metadata       |
The types Classification, Identifier and Metadata should all be links to where the object is defined

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +  "resourceType": "livestock/animal-group"
```suggestion
  "resourceType": "/livestock/animal-group"
```

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +# Resource Type: Animal Group
I'm not sure whether we are going for "Animal Group" vs "Animal Groups" in this title - do whatever is consistent with most of the other documentation pages

2022-11-24 19:55 UTC, danielR9 commented on docs/resource-types/livestock/index.md
> +- [Animal Group](/resource-types/livestock/animal-group.md)
Make the plural here consistent with whatever we title the main page as

2022-11-25 02:15 UTC, ryanjosephtorrado commented
Hey @danielR9 , I've updated the documentation. Please check and review. Thank you

2022-11-25 02:57 UTC, danielR9 requested changes

2022-11-25 02:57 UTC, danielR9 commented on docs/resource-types/livestock/animal-group.md
> +| **Meta**           | Meta data for the resource                                                                     | [Metadata](/docs/resource-types/common.md#metadata)     |
```suggestion
| **Meta**           | Meta data for the resource                                                                     | [Metadata](/resource-types/common.md#metadata)     |
```

2022-11-25 04:21 UTC, danielR9 approved these changes

2022-11-25 04:22 UTC, merged