feat(group-treatment-event): add group treatment event documentation
Pure-Farming/Documentation pull request #18
Opened 2022-12-08 22:39 UTC by ryanjosephtorrado

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-12-12 19:49 UTC, chriiiish commented
🦄

2022-12-13 10:40 UTC, ryanjosephtorrado commented
@chriiiish I've updated the documentation and added notes for reference. Please review and leave a comment. Thank you

2022-12-13 18:11 UTC, danielR9 requested changes

2022-12-13 18:11 UTC, danielR9 commented on docs/resource-types/index.md
> +  - [Treatments](/docs/resource-types/livestock/treatments/index.md)
Don't think these are supposed to contain `docs`. Same with other links

2022-12-14 19:08 UTC, chriiiish commented on docs/resource-types/index.md
> +_Pure Farming_ APIs are designed to deliver standardised and cleansed data relating to all types currently supported resource types.
```suggestion
_Pure Farming_ APIs are designed to deliver standardised and cleansed data relating to all currently supported resource types.
```

2022-12-14 19:10 UTC, chriiiish commented on docs/resource-types/index.md
> +    Although it is smaller than the holdings but is a quite substantial piece of land.
```suggestion
    It is smaller piece of land than a holding (a holding can have many plots).
```

2022-12-14 19:11 UTC, chriiiish commented on docs/resource-types/index.md
> +    Defines a group of animals in a medium-long sense (for instance, a mob or pen or batch or class or line).
```suggestion
    Defines a group of animals in a medium-long term sense (for instance, a mob or pen or batch or class or line).
```

2022-12-14 19:13 UTC, chriiiish commented on docs/resource-types/index.md
> +    - [Group Treament Event](/resource-types/livestock/treatments/group-treament-event.md) Event for recording treatment of a group of animals.
```suggestion
    - [Group Treament Event](/resource-types/livestock/treatments/group-treament-event.md) Event for recording a medical treatment on a group of animals.
```

2022-12-14 19:15 UTC, chriiiish commented on docs/resource-types/index.md
> +  - [Milk Collection](/resource-types/dairy/milk-collection.md)
```suggestion
    - [Milk Collection](/resource-types/dairy/milk-collection.md) Collection of milk from a location
```

2022-12-14 19:18 UTC, chriiiish commented on docs/resource-types/index.md
> +URI, short for Uniform Resource Identifier, is a unique sequence of characters that identifies a logical or physical resource used by web technologies.
Wider discussion here - but _are_ these actually frequently asked questions? I'd expect the FAQs to be more PureFarming centered (specifically about _this_ API, rather than about API's in general)

@danielR9 @daniel-buchanan

2022-12-14 19:19 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Get all group greatment gvent that you have access to
```suggestion
Get all group treatment events that you have access to
```

2022-12-14 19:20 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Get all group treatment event associated with a holding
```suggestion
Get all group treatment events associated with a holding
```

2022-12-14 19:20 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +A call to the group treatment event endpoints returns the following fields.
```suggestion
A call to the group treatment event endpoints returns the following fields:
```

2022-12-14 19:23 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Event Date Time**          | A particular point in the progression of time                                                                             | Date/Time
```suggestion
| **Event Date Time**          | The time the event occurred                                                                                                | Datetime                                              |
```

2022-12-14 19:26 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Count Observed**           | Summarises the number of animals observed in the event                                                                    | Number
```suggestion
| **Count Observed**           | The number of animals observed in the event                                                                             | Number                                                |
```

2022-12-14 19:33 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Embedded animal set in Group Treatment Event are...
```suggestion
An embedded animal set is a set of animals embedded in a specific group treatment event.
```

2022-12-14 19:37 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Inventory classification in Group Treatment Event are...
```suggestion
Inventory classifications describe the group of animals by their characteristics rather than animal identifiers
```

2022-12-14 19:39 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Medicine in Group Treatment Event are...
```suggestion
The medication used for treatment of the animals
```

2022-12-14 19:42 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Href**                  | Where provided, this is the URI to the referenced resource                                                                      | URI
```suggestion
| **Href**                  | Where provided, this is the URI to the medication information page                                                              | URI                                                         |
```

2022-12-14 19:42 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Withdrawals in Group Treatment Event are...
```suggestion
Withholding details for the treatment administered
```

2022-12-14 19:44 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **End Date**     | A particular point in the progression of time                                                           | Date/Time   |
```suggestion
| **End Date**     | The end date for this withholding period                                                               | Datetime    |
```

2022-12-14 19:44 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +Batches in Group Treatment Event are...
```suggestion
Batches and expiry details for the medicine administered
```

2022-12-14 19:45 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Expiry Date** | A particular point in the progression of time | Date/Time |
```suggestion
| **Expiry Date** | The expiry date of the medication             | Datetime  |
```

2022-12-14 19:50 UTC, chriiiish commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +### Dose per Animal
Just have one `Dosage` object that is used for both
* Dose Per Animal
* Medicine Used

You'll need to:
- Update this section to be "Dosage"
- Update the references on line 102+103

2022-12-16 00:54 UTC, danielR9 approved these changes

2022-12-16 00:54 UTC, danielR9 commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Group Method**             | Indicates whether the event references an existing animal set, has an embedded animal set, or an inventory classification | Enumeration
```suggestion
| **Group Method**             | Indicates whether the event references an existing animal set, has an embedded animal set, an inventory classification or both an inventory classification and animal set | Enumeration                                           |
```

2022-12-16 00:54 UTC, danielR9 commented on docs/resource-types/livestock/treatments/group-treament-event.md
> +| **Member**        | Identifies an animal using a scheme and ID                                                  | Array of [Identifiers](/resource-types/common.md#identifier) |
I think we might end up moving this to a standalone thing, but could be ok for now. As it needs to be referenced by any other group events/data

2022-12-16 01:40 UTC, chriiiish submitted a review, later dismissed

2022-12-16 02:32 UTC, danielR9 approved these changes

2022-12-16 02:34 UTC, merged