feat: add group weight event documentation
Pure-Farming/Documentation pull request #19
Opened 2022-12-14 23:21 UTC by sb226

Ticket: ab#17423
----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-12-16 00:48 UTC, chrishogg reviewed
Only found very minor typo :-)

2022-12-16 00:48 UTC, chrishogg commented on docs/resource-types/livestock/weights/group-weight-event.md
> +```
should it be; **HoldingId**?

2022-12-18 19:20 UTC, danielR9 requested changes

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/index.md
> +_Pure Farming_ data APIs are designed to deliver data for a range of different agricultural resources, which are standardised to a common schema regardless of the original data sources that provided
Why is this changing?

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/index.md
> +The _Pure Farming_ API is provided as a SaaS offering and the endpoints that you will be interested in are:
Same query here - what is the change, and why from `*Pure Farming*` to  `_Pure Farming_`?

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/index.md
> +Below are the currently provided resource types for Livestock.
```suggestion
Below are the currently provided resource types for livestock weights.
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Metric** | The metric code for a specific statistic. | [Identifier](https://github.com/adewg/ICAR/wiki/Schemes#identification-and-enum-schemes) |
Shouldn't this link to our docs for an identifier type, not the ICAR json schema?

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Type** | Deprecated - Specifies whether this is a single Device a Link or a Collection. | Enumeration |
What do all these deprecated comments mean? Is it deprecated in the schema? Have we deprecated it in our response? If we are never going to provide them, then should we remove from our docs (as we don't have an old verison to support)

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Weight** | The weight measurement. | Number |
Do we need to mention the units of all these weights are specified in the root object

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +### Animal Set Reference
This and Embedded Animal set looks to be copied from group treatment events.
These are going to be common to all group related stuff - can these definitions be moved to somewhere more common and referenced from here

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Event Date Time** | A particular point in the progression of time. | [Datetime](https://ijmacd.github.io/rfc3339-iso8601/) |
This phrasing seems a little too scientific? Can we copy the datetime comments from elsewhere in these docs

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Meta** | Meta data for the resource. | Metadata |
Needs a link to where meta is defined

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Location** | An identifier for the location of the Group Weight Event. | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Location** | An identifier for the location of the Group Weight Event. | [Identifier](/resource-types/common.md#identifier) |
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Trait Label** | Represents a formal trait, identifies the recording system and trait. | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Trait Label** | Represents a formal trait, identifies the recording system and trait. | [Identifier](/resource-types/common.md#identifier) | 
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Identifier** | Identifies a resource. | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Identifier** | Identifies a resource. | [Identifier](/resource-types/common.md#identifier) |
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Member** |  An identifier for the animal of the Animal Set. | Array of [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Member** |  An identifier for the animal of the Animal Set. | Array of [Identifier](/resource-types/common.md#identifier) | 
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Location** | An identifier for the location of the Animal Set. | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Location** | An identifier for the location of the Animal Set. | [Identifier](/resource-types/common.md#identifier) |
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Primary Breed** | Primary breed defined using an identifier and scheme | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Primary Breed** | Primary breed defined using an identifier and scheme | [Identifier](/resource-types/common.md#identifier) |
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Animal** | Animal defined using an identifier and scheme | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Animal** | Animal defined using an identifier and scheme | [Identifier](/resource-types/common.md#identifier) | 
```

2022-12-18 19:20 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Identifier** | Device defined using an identifier and scheme. | [Identifier](/docs/resource-types/common.md#identifier) |
```suggestion
| **Identifier** | Device defined using an identifier and scheme. | [Identifier](/resource-types/common.md#identifier) |
```

2022-12-18 20:53 UTC, sb226 commented on docs/resource-types/index.md
> +The _Pure Farming_ API is provided as a SaaS offering and the endpoints that you will be interested in are:
* or _ still still turn your letter into a pisa tower I think

2022-12-18 20:59 UTC, danielR9 commented on docs/resource-types/index.md
> +The _Pure Farming_ API is provided as a SaaS offering and the endpoints that you will be interested in are:
Yeah, but why are we changing the styling of the index page? And why doing it in the livestock weights docs PR?

2022-12-18 21:06 UTC, sb226 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Meta** | Meta data for the resource. | Metadata |
Link to our metadata that in the Document contain these property:
{ 
"created": "2022-07-06T10:11:21.460Z", 
"creator": "string", 
"modified": "2022-07-06T10:11:21.460Z", 
"sourceId": { … }, 
"validFrom": "2022-07-06T10:11:21.460Z", 
"validTo": "2022-07-06T10:11:21.460Z" 
}

But GroupWeight Metadata contain these property:
{ 
"created": "2022-12-18T21:04:34.059Z", 
"creator": "string", 
"isDeleted": true, 
"modified": "2022-12-18T21:04:34.059Z", 
"source": "string", 
"sourceId": "string", 
"validFrom": "2022-12-18T21:04:34.059Z", 
"validTo": "2022-12-18T21:04:34.059Z" 
}

Is it going to be ok if I still link it to the "metadata that in the Document" one?

2022-12-18 21:14 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Meta** | Meta data for the resource. | Metadata |
We have 2 different metadata objects from. The one in common.md is the Datalinker/Geospatial sourced one, and the one here is the ICAR sourced one. We probably want this metadata to be common in the livestock directory, and reference it there. And probably the one currently in common.md should be moved to /core as it is  geospatial

2022-12-18 22:19 UTC, sb226 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Type** | Deprecated - Specifies whether this is a single Device a Link or a Collection. | Enumeration |
So on the schema said it's Deprecated but it's still exist in the example response / object

2022-12-19 00:56 UTC, sb226 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +### Animal Set Reference
@danielR9 should I create a common.md for livestock?

2022-12-19 01:41 UTC, sb226 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Weight** | The weight measurement. | Number |
I don't see any enum value for those

2022-12-20 01:02 UTC, VicXue submitted a review, later dismissed

2022-12-20 01:44 UTC, VicXue approved these changes

2022-12-20 03:30 UTC, danielR9 commented on docs/resource-types/livestock/weights/group-weight-event.md
> +| **Weight** | The weight measurement. | Number |
Yeah - because the unit is in the root object. So not documenting here that units could be KGM etc, but I would have commented that when this has an array of weights, the unit of the weight is defined somewhere else (not in this array)

2022-12-20 03:56 UTC, merged