Chore/17386 medicine product docs
Pure-Farming/Documentation pull request #25
Opened 2023-01-16 00:23 UTC by AndyDe-Aldent

----

Filling in the documentation for the medicine product

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [x] Links work to navigate documentation
- [ ] ~~Images stored in `_images`~~
- [x] Spell checked

> If some of the above are not completed why?
> No Images added

2023-01-16 01:16 UTC, VicXue requested changes

2023-01-16 01:16 UTC, VicXue commented on docs/reference/treatment/medicine-products.md
> +| **Species**| The species that may be treated by this medicine.| Array icarAnimalSpecieType|
Can we list the enumeration values or hyperlink to the actual definition in iCar?

2023-01-16 01:16 UTC, VicXue commented on docs/reference/treatment/medicine-products.md
> +| **Active Ingredients**| The active ingredients in the medicine.| Array medicine-ingredient-type |
There is no definition of this type: medicine-ingredient-type

2023-01-16 22:01 UTC, AndyDe-Aldent commented on docs/reference/treatment/medicine-products.md
> +| **Active Ingredients**| The active ingredients in the medicine.| Array medicine-ingredient-type |
added definitions for both the medicine-ingredient-type and the medicine-withholding-type

2023-01-23 02:34 UTC, VicXue submitted a review, later dismissed

2023-01-23 19:47 UTC, VicXue approved these changes

2023-01-23 19:48 UTC, merged