19494 group arrival documentation
Pure-Farming/Documentation pull request #26
Opened 2023-01-20 00:13 UTC by AndyDe-Aldent

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [x] Links work to navigate documentation
- [ ] ~~Images stored in `_images`~~
- [x] Spell checked

> If some of the above are not completed why?
> no images added

2023-01-20 03:51 UTC, danielR9 commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Consignment** | Consignment information for a movement (arrival, departure). [See the Consignment definition](/resource-types/livestock/movements/consignment.md) | Consignment |
Would it be more consistent to put the link in the data type column?

2023-01-20 03:51 UTC, danielR9 commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Event Date Time**| The Time that this event occurred. | DateTimeOffset |
I know it is a .NET DateTimeOffset, but I don't think we specified this for all the other datetime responses

2023-01-23 18:55 UTC, markusPirkl commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Event Date Time**| The Time that this event occurred. | DateTimeOffset |
This would need to change here too https://github.com/Pure-Farming/Documentation/blob/497bd529234edac4f268cc3708e6f6f56e52583d/docs/resource-types/livestock/movements/group-arrival.md?plain=1#L65

2023-01-23 19:03 UTC, markusPirkl commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Explanation** | Free text explanation of the reason for death. | String |
This should probably say arrival. :D

2023-01-23 19:03 UTC, markusPirkl commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Location** | An identifier for the location of the Animal Death. | [Identifier](/resource-types/common#identifier) |
Needs to talk about Arrival as well.

2023-01-23 19:04 UTC, markusPirkl commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Self** | A link to this specific Animal Death. | URI |
Arrival

2023-01-23 19:04 UTC, markusPirkl requested changes
see comments

2023-01-23 19:13 UTC, AndyDe-Aldent commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Event Date Time**| The Time that this event occurred. | DateTimeOffset |
most of the other EventDateTime fields on the existing movement are already a DateTimeOffset

2023-01-23 19:15 UTC, AndyDe-Aldent commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Consignment** | Consignment information for a movement (arrival, departure). [See the Consignment definition](/resource-types/livestock/movements/consignment.md) | Consignment |
moved the link into the data type column thoughout the movement documentation

2023-01-23 19:24 UTC, AndyDe-Aldent commented on docs/resource-types/livestock/movements/group-arrival.md
> +|**Event Date Time**| The Time that this event occurred. | DateTimeOffset |
updated to follow the birth registration.

2023-01-24 17:57 UTC, markusPirkl approved these changes
👍

2023-01-24 18:48 UTC, merged