Feat pasture cover documentation
Pure-Farming/Documentation pull request #38
Opened 2023-03-07 23:12 UTC by sb226

Ticket: AB#20064
----

Notes
Documenting pasture cover event 

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2023-03-08 00:44 UTC, chriiiish requested changes

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/index.md
> +  - [Pasture Cover](/resource-types/crops/pasture-cover-event.md)
```suggestion
  - [Pasture Cover](/resource-types/crops/pasture-cover-event.md)  
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/index.md
> +  - [Pasture Cover](/resource-types/crops/pasture-cover-event.md)
Adding the double-space at the end puts the description on the line below (at least in markdown)

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +Get all Pasture Cover Events that you have access to.
```suggestion
Get all Pasture Cover events that you have access to.
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +Get a single Pasture Cover Events for the specified **pastureCoverEventId**, the Id is required.
```suggestion
Get a single Pasture Cover event, specified by its ID
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +Get all Pasture Cover Events that are linked to the provided **HoldingId**, holding Id is required.
```suggestion
Get all Pasture Cover events for a given holding
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +Get a single Pasture Cover Events with a given **HoldingId** and **pastureCoverEventId**, both Ids are required.
Get a single Pasture Cover event, specified by its Holding ID and ID

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Identifiers**| Any identifiers for this Pasture Cover Events.| Array of [Identifiers](/resource-types/common.md#identifier)|
```suggestion
|**Identifiers**| Any identifiers for this Pasture Cover event.| Array of [Identifiers](/resource-types/common.md#identifier)|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Observation Date**|UTC Date (required) and time (optional) the milk collection was taken.|Date/Time|
```suggestion
|**Observation Date**|UTC Date and time the milk collection was taken.|Datetime|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Feature**|The feature that this operation performed on |[Feature](/resource-types/common.md/#feature)|
```suggestion
|**Feature**|The feature that this event occurred on |[Feature](/resource-types/common.md/#feature)|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Holding**|The holding where the Pasture Cover Event was recorded.|[Feature](/resource-types/common.md/#feature)|
```suggestion
|**Holding**|The holding where the event was recorded.|[Feature](/resource-types/common.md/#feature)|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Phenomenon Start Time**|ISO UTC DateTime for when the Pasture Cover Event started|Date/Time|
```suggestion
|**Phenomenon Start Time**| UTC Date and time when the Pasture Cover event started |Datetime|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +| **Phenomenon End Time** | ISO UTC DateTime for when the Pasture Cover Event ended | Date/Time|
```suggestion
|**Phenomenon End Time**| UTC Date and time when the Pasture Cover event ended |Datetime|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Pasture Area**|Area of the feature in pasture.|[Area Measurement Type](#area-measurement-type)|
I think for these links to work they need to have %20's in them (because whatever generates the page only puts dashes in for the first one)
```suggestion
|**Dry Matter**| Pasture dry matter yield calculated or estimated.| [Dry Matter Measure Type](#dry-matter%20measure%20type)|
|**Pasture Height**| Average pasture height of the feature.| [Length Measure Type](#length-measure%20type)|
|**Pasture Area**|Area of the feature in pasture.|[Area Measurement Type](#area-measurement%20type)|
```

2023-03-08 00:44 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +| **Manu Facturer** | Defines the relationship between the current resource and the referenced resource. | String |
```suggestion
| **Manufacturer** | The maker of the device | String |
```

2023-03-08 00:46 UTC, sb226 commented
@chriiiish Cheeseus

2023-03-08 00:48 UTC, sb226 commented on docs/resource-types/index.md
> +  - [Pasture Cover](/resource-types/crops/pasture-cover-event.md)
woah magic

2023-03-10 01:22 UTC, chriiiish requested changes

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Id**| The *Pure Farming* Id of this Pasture Cover Event.|UUID|
```suggestion
|**Id**| The *Pure Farming* Id of this Pasture Cover event.|UUID|
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Observation Date**|UTC Date and time the event was observed.|DateTime|
```suggestion
|**Observation Date**|UTC date and time the event was observed.|DateTime|
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/load-receival.md
> +|**Observation Date**|UTC Date and time the load-receival was taken.|DateTime|
```suggestion
|**Observation Date**|UTC date and time the load was received.|DateTime|
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +|**Phenomenon Start Time**| UTC Date and time when the Pasture Cover event started|DateTime|
```suggestion
|**Phenomenon Start Time**| UTC date and time when the Pasture Cover event started.|DateTime|
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/pasture-cover-event.md
> +| **Phenomenon End Time** | UTC Date and time for when the Pasture Cover event ended | DateTime|
```suggestion
| **Phenomenon End Time** | UTC date and time for when the Pasture Cover event ended. | DateTime|
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/sample-analysis.md
> +| **Observation Date** | UTC Date and time the Sample analyses was taken| DateTime |
```suggestion
| **Observation Date** | UTC date and time the sample analyses were taken| DateTime |

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/sample-plan.md
> +| **Observation Date** | UTC Date and time the Sample Plan was taken.| DateTime |
```suggestion
| **Observation Date** | UTC date and time the sample plan was put in place.| DateTime |

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/crops/work-record.md
> +| **Phenomenon End Time** | UTC Date and time for when the Pasture Cover event ended | DateTime
```suggestion
| **Observation Date** | UTC date and time when the work record was observed | DateTime|
| **Phenomenon Start Time** | UTC date and time when the work started | DateTime
| **Phenomenon End Time** | UTC date and time for when the work ended | DateTime
```

2023-03-10 01:22 UTC, chriiiish commented on docs/resource-types/dairy/milk-collection.md
> +|**Observation Date** | UTC Date and time the milk collection was taken. | Date/Time
```suggestion
|**Observation Date** | UTC date and time the milk collection was taken. | DateTime

2023-03-10 01:23 UTC, chriiiish approved these changes

2023-03-10 01:25 UTC, merged