feat: added documentation for inventory - medicine transaction.
Pure-Farming/Documentation pull request #60
Opened 2023-07-28 14:17 UTC by satbir-93

[AB#23639](https://dev.azure.com/rezaresystems/15020b92-fee6-4202-956f-9036d1e1da84/_workitems/edit/23639)

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2023-07-30 20:29 UTC, AndyDe-Aldent requested changes

2023-07-30 20:29 UTC, AndyDe-Aldent commented on docs/resource-types/inventory/medicine-transaction.md
> +---
Can you add in the information and URLs for accessing the Medicine Transactions via the streaming API here as well.

2023-07-31 04:00 UTC, satbir-93 commented on docs/resource-types/inventory/medicine-transaction.md
> +---
@AndyDe-Aldent Doesn't seem like streaming info is there for all other APIs out there?

![image](https://github.com/Pure-Farming/Documentation/assets/26356115/ec2e121e-99e7-4843-83b5-9823b10eb2e6)

2023-07-31 04:09 UTC, AndyDe-Aldent approved these changes

2023-07-31 04:09 UTC, merged