feat(auth): add authentication landing page
Pure-Farming/Documentation pull request #9
Opened 2022-10-30 21:46 UTC by laura-thresh

----

Notes

----

## PR Checklist
- [ ] Documentation has been checked by at least one team member
- [ ] Links work to navigate documentation
- [ ] Images stored in `_images`
- [ ] Spell checked

> If some of the above are not completed why?
> **REASON HERE**

2022-11-02 03:16 UTC, danielR9 approved these changes
Couple of minor grammar things - feel free to ignore them. I know the text hasn't actually changed in this PR and this stuff is already on devhub

2022-11-02 03:16 UTC, danielR9 commented on docs/authentication/scenarios.md
> +Pure Farming APIs use PKCE, short for proof key for code exchange, authorisation code flow. In order to make Pure Farming API requests, users will need to obtain an access token and refresh token. Th
```suggestion
Pure Farming APIs use proof key for code exchange (PKCE) authorisation code flow. In order to make Pure Farming API requests, users will need to obtain an access token and refresh token. The application needs to redirect the user to the authorisation endpoint https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/auth with the client ID and code challenge.  
```

2022-11-02 03:16 UTC, danielR9 commented on docs/authentication/index.md
> +OAuth 2.0, short for Open Authorisation, is an authorisation protocol that enables applications to obtain limited access to resources on an HTTP service. This authorisation standard protects user dat
```suggestion
OAuth 2.0 is an authorisation protocol that enables applications to obtain limited access to resources on an HTTP service. This authorisation standard protects user data by providing access to the data without revealing the user’s identity or credentials. It uses username and password tokens instead.  
```

I'm just not a fan of "short for" - isn't OAuth2.0 standard enough we don't need to define it?

2022-11-13 06:41 UTC, daniel-buchanan requested changes
See comments.

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/basic-steps.md
> +- [**Step 5:** Refresh the access token](#step5)
These will all need to be changed, the way that the code in WP generates the links is as follows:
`Step 1: Obtain Client ID and Client Secret` becomes `#step-1:-obtain-client-id-and-client-secret`

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/basic-steps.md
> +https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/token
```suggestion
```
https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/token 
```
```

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/index.md
> +**Authorisation:** https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/auth
```suggestion
**Authorisation:** `https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/auth`
```

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/index.md
> +**Token:** https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/token
```suggestion
**Token:** `https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/token`
```

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/index.md
> +**User Info:** https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/userinfo
```suggestion
**User Info:** ~https://signin.purefarming.com/auth/realms/moa/protocol/openid-connect/userinfo`
```

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/index.md
> +
We need a ToC or something that links to the other pages here.

2022-11-13 06:41 UTC, daniel-buchanan commented on docs/authentication/scenarios.md
> +- [Applications not authenticated with Pure Farming](#NotAuthenticated)
Same rules as above apply here.

2022-11-14 00:56 UTC, daniel-buchanan submitted a review, later dismissed

2022-11-14 01:33 UTC, daniel-buchanan approved these changes

2022-11-14 01:33 UTC, merged